import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { ToastController } from '@ionic/angular';
import { ActivatedRoute } from '@angular/router';
import { NavController } from '@ionic/angular';

@Component({
  selector: 'app-viaje',
  templateUrl: './viaje.page.html',
  styleUrls: ['./viaje.page.scss'],
})
export class ViajePage implements OnInit {
 productos: any[]=[
   {"id":1,"Pais":"Mexico","Ciudad":"San Miguel de Allende (Guanajuato)","Hotel":"1500","Comida":"1200","Viaje":"700","Actividades":"320","Distancia":"270km","Description":"Un viaje a San Miguel de Allende desde la ciudad de Mexico. La ciudad de San Miguel de Allende cuenta con una buena arquitectura y la parroquia de San Miguel de Arcángel inspirada en las iglesias góticas del antiguo continente. Esta ciudad obtuvo en 2020 el Sello de Viaje Seguro del Consejo Mundial de Viajes y Turismo (WTTC) y fue la segunda mejor ciudad del mundo para viajar por los premios World 's Best Awards en 2020.","images":["../../assets/img/p1/p1.jpg"]},
   {"id":2,"Pais":"Mexico","Ciudad":"Cancun","Hotel":"3433","Comida":"2450","Viaje":"2766","Actividades":"1461","Distancia":"1,610km","Description":"Cancún es una ciudad de México ubicada en la península de Yucatán que limita con el mar Caribe y que es conocida por sus playas, los numerosos centros turísticos y la vida nocturna. Se compone de 2 áreas distintas: el área del centro más tradicional y la Zona Hotelera, la franja costera con hoteles altos, clubes nocturnos, tiendas y restaurantes. Cancún también es un destino popular entre estudiantes durante el período de vacaciones universitarias en la primavera.","images":["../../assets/img/p1/p2.jpg"]},
   {"id":3,"Pais":"Mexico","Ciudad":"Ciudad de Mexico","Hotel":"1500","Comida":"400","Viaje":"1321","Actividades":"890","Distancia":"0","Description":"Ciudad de México es la densamente poblada capital de México que se encuentra a gran altura. Es famosa por su Templo Mayor (un templo azteca del siglo XIII), la Catedral Metropolitana de México, de estilo barroco, de los conquistadores españoles y el Palacio Nacional, que alberga murales históricos de Diego Rivera. ","images":["../../assets/img/p1/p3.jpg"]},
   {"id":4,"Pais":"Indonesia","Ciudad":"Yakarta","Hotel":"655","Comida":"520","Viaje":"48193","Actividades":"1380","Distancia":"16,835","Description":"Yakarta, la enorme capital de Indonesia, se ubica en la costa noroeste de la isla de Java. La mezcla histórica de culturas (javanesa, malaya, china, árabe, india y europea) influyó en su arquitectura, su idioma y su gastronomía.","images":["../../assets/img/p2/p1.jpg"]},
   {"id":5,"Pais":"Indonesia","Ciudad":"Ubud","Hotel":"814","Comida":"531","Viaje":"46465","Actividades":"1000","Distancia":"15,648","Description":"La ciudad de Ubud, en las alturas de Bali, Indonesia, es conocida como un centro de danza y artesanía tradicional. El bosque pluvial y los arrozales en terrazas del distrito de Ubud circundante, con templos y santuarios hindúes, se encuentran entre los paisajes más famosos de Bali. Entre los lugares sagrados antiguos, se encuentran Goa Gajah (la Cueva del Elefante), con sus complejos tallados, y Gunung Kawi, con sus santuarios tallados en piedra","images":["../../assets/img/p2/p2.jpg"]},
   {"id":6,"Pais":"Indonesia","Ciudad":"Surabaya","Hotel":"589","Comida":"465","Viaje":" 86747","Actividades":"935","Distancia":"16,308km","Description":"Surabaya es una metrópoli e importante puerto de Indonesia, situada en la costa norte de la isla de Java, sobre la boca del río Mas y a un lado del estrecho de Madura. Surabaya es capital de la provincia de Java Oriental y cuenta con 3.520.874 habitantes, siendo la segunda metrópoli más poblada del país","images":["../../assets/img/p2/p3.jpg"]},
   {"id":7,"Pais":"Nueva Zelanda","Ciudad":"Auckland ","Hotel":"1438","Comida":"1600","Viaje":"47,170","Actividades":"770","Distancia":"270km","Description":"Conocida como la ciudad de las velas, Auckland es la localidad más grande de Nueva Zelanda y una de las más llamativas. Ha sido bendecida con un espectacular paseo marítimo, un magnífico horizonte y numerosasplayas.","images":["../../assets/img/p3/p1.jpg"]},
   {"id":8,"Pais":"Nueva Zelanda","Ciudad":"Wellington ","Hotel":"1438","Comida":"1700","Viaje":"48,742","Actividades":"930","Distancia":"270km","Description":"Situada en un bucólico entorno junto al mar, Wellington es la capital de un mundo en miniatura llamado Nueva Zelanda. En esta tierra de película te esperan playas de ensueño, espectaculares fiordos, piscinas geotérmicas, selvas tropicales, impresionantes glaciares y bosques encantados.","images":["../../assets/img/p3/p2.jpg"]},
   {"id":9,"Pais":"Nueva Zelanda","Ciudad":"Queenstown ","Hotel":"2242","Comida":"1400","Viaje":"45,111","Actividades":"2,636","Distancia":"11,683km","Description":"Esta ciudad es una de las más bonitas de la isla sur de Nueva Zelanda. Además, Queenstown es la capital mundial de los deportes de aventura. A través de sus valles, lagos, montañas y ríos se pueden realizar todo tipo de deportes como parapente, puenting, deportes acuáticos, rutas de trekking, etc.","images":["../../assets/img/p3/p3.jpg"]},
   {"id":10,"Pais":"Colombia","Ciudad":"Medellín","Hotel":"565","Comida":"144","Viaje":" 4442,76","Actividades":"460","Distancia":"2,938 km","Description":"Es la capital del departamento de Antioquia y la segunda ciudad más poblada del país después de Bogotá. Tambien su clima es mayormente templado llegando a ser reconocida como la ciudad de la Eterna Primavera","images":["../../assets/img/p4/p1.jpg"]},
   {"id":11,"Pais":"Colombia","Ciudad":"Bogotá","Hotel":"1112","Comida":"158","Viaje":"5834 ","Actividades":"1200","Distancia":"3169km","Description":"Bogotá es la capital y ciudad más poblada de Colombia. Tiene más de siete millones de habitantes, lo que la convierte en una de las grandes urbes del continente sudamericano. Aunque existían asentamientos indígenas precolombinos, la fundación de facto de la ciudad se produjo en 1538 por los españoles.","images":["../../assets/img/p4/p2.jpg"]},
   {"id":12,"Pais":"Colombia","Ciudad":"Santa Marta","Hotel":"519","Comida":"177","Viaje":"8841","Actividades":"760","Distancia":" 2,822 km","Description":"Santa Marta es el segundo puerto maritimo de Colombia en el oceano Atlantico. Aparte de sus bellas playas en Santa Maria se encuentra la Sierra Nevada de Santa Marta la cual es la montaña intertropical más alta del mundo a la orilla del mar","images":["../../assets/img/p4/p3.jpg"]},
   {"id":13,"Pais":"India","Ciudad":"Delhi","Hotel":"3218","Comida":"214","Viaje":"22414","Actividades":"584.47","Distancia":"14638km","Description":"Delhi es la capital de la República de la India y también una ciudad con fines administrativos. Es una de las metrópolis más grandes del país. Delhi comparte sus fronteras con los estados de Uttar Pradesh y Haryana. Es el centro de la política internacional, el comercio, la cultura y la literatura en la India.","images":["../../assets/img/p5/p1.jpg"]},
   {"id":14,"Pais":"India","Ciudad":"Bombai","Hotel":"2562","Comida":"462","Viaje":" 26224","Actividades":"436","Distancia":"15636km","Description":"Bombay también conocida como Mumbai, es la capital del estado federal de Maharashtra. Es la ciudad más poblada de la India y la cuarta más poblada del mundo. La ciudad se encuentra en la costa del mar Arábigo en el oeste de la India, y tiene un puerto natural de gran profundidad.","images":["../../assets/img/p5/p2.jpg"]},
   {"id":15,"Pais":"India","Ciudad":"Bangalore","Hotel":"1940","Comida":"320","Viaje":"33376","Actividades":"734","Distancia":"16384km","Description":"Bangalore es la capital del estado de Karnataka, en la India. Es conocida como la ciudad jardín (Garden City), debido a la cantidad de árboles y flores que contiene. Su población es de 4,5 millones de habitantes, lo que la convierte en la cuarta mayor ciudad del país.","images":["../../assets/img/p5/p3.jpg"]},
   {"id":16,"Pais":"Francia","Ciudad":"Paris","Hotel":"1549 ","Comida":"1130","Viaje":" 27800","Actividades":"742","Distancia":"9,210km","Description":"  París, una de las más bonitas ciudades del mundo, seduce en primer lugar por su excepcional patrimonio arquitectónico y cultural. Un patrimonio vivo, que no deja de modernizarse y enriquecerse. París es también la capital de la gastronomía, de la moda y de las compras.","images":["../../assets/img/p6/p1.jpg"]},
   {"id":17,"Pais":"Francia","Ciudad":"Niza","Hotel":"2351","Comida":"659","Viaje":" 28215","Actividades":"752","Distancia":"9,766km","Description":" Niza es una ciudad de Francia que se encuentra frente al mar Mediterráneo, en el sureste del país, cerca de la frontera con Italia. Es la capital de la Riviera Francesa o Costa Azul, una zona turística con un clima templado y una arquitectura elegante. Es la segunda ciudad más poblada de la costa sur de Francia, después de Marsella, y la ciudad con más museos en Francia, después de París","images":["../../assets/img/p6/p2.jpg"]},
   {"id":18,"Pais":"Francia","Ciudad":"Marsella","Hotel":"1054","Comida":"941","Viaje":" 23270","Actividades":"821","Distancia":"9,647km","Description":" Marseille es ciudad más antigua de Francia, ya que fue fundada por los foceos en el año 600 a. C. Después de que los romanos dejaron su huella, la ciudad siguió desarrollándose mediante una verdadera mezcolanza de culturas, alrededor del puerto Viejo, protegido por sus dos fuertes, Saint-Nicolas y Saint-Jean.","images":["../../assets/img/p6/p3.jpg"]},
   {"id":19,"Pais":"Ecuador","Ciudad":"Quito","Hotel":"1355","Comida":"382","Viaje":"5941","Actividades":"151.25","Distancia":"3134km ","Description":"Quito, la capital de Ecuador, se encuentra a más de 2800 msnm y está rodeada de volcanes como el Pichincha y el Atacazo que superan los 4000. Cuenta con algo más de un millón y medio de habitantes.","images":["../../assets/img/p7/p1.jpg"]},
   {"id":20,"Pais":"Ecuador","Ciudad":"Guayaquil","Hotel":"1732","Comida":"179","Viaje":"4989","Actividades":"132.41","Distancia":" 3192km","Description":"Santiago de Guayaquil es la ciudad más poblada de la República del Ecuador. El área urbana de Guayaquil la ubica entre las ciudades más grandes del mundo. Es además un importante centro de comercio con influencia a nivel regional en el ámbito comercial, de finanzas, cultural, y de entretenimiento.","images":["../../assets/img/p7/p2.jpg"]},
   {"id":21,"Pais":"Ecuador","Ciudad":"Manta","Hotel":"1936","Comida":"342","Viaje":" 7676","Actividades":"143.57","Distancia":"3029km","Description":"Manta es el primer puerto turístico, marítimo y pesquero del Ecuador. Está asentado en una espléndida bahía, que le ha dado la característica de puerto internacional en el Océano Pacífico.","images":["../../assets/img/p7/p3.jpg"]},
   {"id":22,"Pais":"Estados Unidos","Ciudad":"Nueva York","Hotel":"3587","Comida":"4636.37","Viaje":" 8915","Actividades":"25375.95","Distancia":"4,109.2km","Description":"Nueva York es la ciudad más poblada del Estado de Nueva York, en los Estados Unidos de América, y la segunda aglomeración urbana del continente. Es el centro del área metropolitana de Nueva York, la cual está entre las cinco aglomeraciones urbanas más grandes del mundo.","images":["../../assets/img/p8/p1.jpg"]},
   {"id":23,"Pais":"Estados Unidos","Ciudad":"Boston","Hotel":"4413","Comida":"225","Viaje":" 10512","Actividades":"1304.85","Distancia":"4,463.7km","Description":"Boston es una ciudad pequeña, pero encantadora. Es la capital del estado de Massachusetts, en Estados Unidos. Se caracteriza por ser una de las ciudades más antiguas del país y estar cargada de historia, cultura y lugares emblemáticos.","images":["../../assets/img/p8/p2.jpg"]},
   {"id":24,"Pais":"Estados Unidos","Ciudad":"Ohio","Hotel":"2182","Comida":"1129","Viaje":"17544 ","Actividades":"2430","Distancia":"3,544 km","Description":"Es uno de los cincuenta estados de los Estados Unidos, situado en la Región de los Grandes Lagos y uno de sus principales centros industriales. Localizado en el Medio Oeste de Estados Unidos (la región más industrializada del país), Ohio tiene a la industria como su principal fuente de ingresos. Otras fuentes de ingresos importantes son las finanzas, la minería del carbón (que ayudó a hacer de Ohio una de las principales potencias industriales del país), la agricultura y el turismo.","images":["../../assets/img/p8/p3.jpg"]},
   {"id":25,"Pais":"Japon","Ciudad":"Tokio","Hotel":"1400","Comida":"772","Viaje":" 37620","Actividades":"1015","Distancia":"11,325km","Description":" Tokio (Tokyo en inglés) es la capital de Japón y la metrópolis más grande del mundo con 34,5 millones de habitantes. La densidad de población es el doble que la de, por ejemplo, Nueva York.La ciudad de Tokio (ocho millones y medio) cuenta con 23 barrios y es la zona que concentra los principales lugares de interés turístico.","images":["../../assets/img/p9/p1.jpg"]},
   {"id":26,"Pais":"Japon","Ciudad":"Osaka","Hotel":"920","Comida":"741","Viaje":"43263","Actividades":"635","Distancia":"11,698km","Description":" Osaka es una ciudad relajada y llena de encanto, famosa por su gastronomía, ocio y vida nocturna, pero en la que también tienen cabida la historia y la cultura. Hay lugares de interés histórico, entre los que destaca el Castillo de Osaka, donde conocerás la historia japonesa y podrás pasear por sus jardines, especialmente hermosos durante la época de floración de los cerezos en abril.","images":["../../assets/img/p9/p2.jpg"]},
   {"id":27,"Pais":"Japon","Ciudad":"Nagoya","Hotel":"678","Comida":"617","Viaje":" 44279","Actividades":"990","Distancia":"11,563km","Description":" Nagoya es la cuarta ciudad más grande de Japón pero ni de lejos es una de las más visitadas. Ahí se encuentra el Castillo de Nagoya, que dicen ser uno de los más bonitos del país. Fue construido a principios de 1.600 por Tokugawa Ieyasu, uno de los shōguns más importantes del periodo Edo, aunque fue arrasado durante los bombardeos de la II GM.","images":["../../assets/img/p9/p3.jpg"]},
   {"id":28,"Pais":"Italia","Ciudad":"Milan(Lombardía)","Hotel":"5576","Comida":"1900","Viaje":"37150","Actividades":"9,815","Distancia":"270km","Description":"Milán, la capital de la región italiana de Lombardía, tiene algo para impresionar a todos los viajeros. Considerada como la capital mundial de la moda y el diseño, esta ciudad italiana seduce a sus visitantes con su abundante patrimonio cultural y arquitectónico, sus lugares inusuales y su gastronomía. .","images":["../../assets/img/p10/p1.jpg"]},
   {"id":29,"Pais":"Italia","Ciudad":"Maranello(Emilia-Romaña)","Hotel":"2224","Comida":"1718","Viaje":"44537","Actividades":"2640","Distancia":"9,084km","Description":"Maranello es una ciudad al norte de Italia sin monumento alguno, pero que representa una catedral que debe visitar todo aficionado al motor desde que, en 1942, Enzo Ferrari decidiese instalar ahí la sede del que sería el equipo de competición más laureado de todos los tiempos… Maranello tiene un encanto especial. Quizás sea un pueblo sin vida, pero desprende una pasión que atrapa al contemplar que cada calle, comercio, plaza o tienda gira en torno a la marca que representa la máxima pasión por el automóvil deportivo.","images":["../../assets/img/p10/p2.jpg"]},
   {"id":30,"Pais":"Italia","Ciudad":"Palermo(Sicilia)","Hotel":"2,067","Comida":"1500","Viaje":"39,397","Actividades":"2,084","Distancia":"10,502km","Description":"Palermo es un verdadero rompecabezas, una ciudad llena de contrastes, donde la belleza y el abandono a menudo comparten los mismos espacios. La capital siciliana, sin embargo, sigue siendo una de las ciudades más fascinantes de Italia: es una amalgama de pueblos, culturas y tradiciones. Palermo tiene miles de caras: aquí se han reunido y mezclado personas de países lejanos, dejando señales indelebles en la arquitectura y en el alma de sus habitantes.","images":["../../assets/img/p10/p3.jpg"]}
   ];
filteredProducts: any[]=[];
pag: any='';

constructor(private router: Router, toastController: ToastController,private route: ActivatedRoute,private navCtrl: NavController) { }

ngOnInit() {
  let id = this.route.snapshot.paramMap.get('id');
  this.pag=id;
  this.filteredProducts = this.productos.filter(p => {
    return p.Pais.includes(this.pag);
  });
} 
handleChange(event: any){
  const searchTerm= event.detail.value;
  if(searchTerm==''){
    this.filteredProducts = this.productos.filter(p => {
      return p.Pais.includes(this.pag) && p.Description.includes(searchTerm) || p.Pais.includes(this.pag) && p.Ciudad.includes(searchTerm);
    });
  }
  else{
    this.filteredProducts = this.productos.filter(p => {
      return p.Pais.includes(this.pag) && p.Description.includes(searchTerm) || p.Pais.includes(this.pag) && p.Ciudad.includes(searchTerm);
    });
  }
}
Volver(){
  this.router.navigate(['/', 'home']);
}
Viaje(a:string){
  this.navCtrl.navigateForward('/costos/'+ a);
}

}
